// Local AI fallback — used when backend/OpenAI is unavailable
const KB = {
  en: [
    { k:["leaf blight","blight","jhulsa","झुलसा"], r:"🔬 **Leaf Blight Treatment**\n\n1. Remove & burn infected leaves immediately\n2. Apply Mancozeb (2.5g/L) every 7-10 days\n3. Avoid overhead irrigation\n4. Use resistant varieties (HD-2967 for wheat)\n\nUpload a photo in Disease Detection for detailed diagnosis! 🌿" },
    { k:["powdery mildew","safed","white powder"], r:"🔬 **Powdery Mildew**\n\n1. Spray sulfur-based fungicide (2g/L)\n2. Apply neem oil (5ml/L) weekly\n3. Improve air circulation between plants\n4. Avoid excess nitrogen fertilizer\n\nSeverity: Medium — act within 3-5 days." },
    { k:["rust","keet","orange spots"], r:"🔬 **Rust Disease**\n\n1. Apply Propiconazole (0.1%) fungicide\n2. Remove infected parts immediately\n3. Plant early-maturing varieties\n4. Spray preventively before monsoon season\n\nSeverity: High — treat urgently!" },
    { k:["aphid","maahu","माहू","insect","keeda","कीड़ा"], r:"🐛 **Aphid / Pest Control**\n\n1. Spray Imidacloprid (0.5ml/L)\n2. Neem oil (5ml/L) for organic control\n3. Introduce ladybird beetles naturally\n4. Plant marigold as trap crop nearby\n\nCheck weekly — aphids spread fast!" },
    { k:["disease","rog","रोग","infection","bimari","बीमारी"], r:"🔬 **Crop Disease Help**\n\nCommon diseases by crop:\n🌾 Wheat — Rust, Leaf Blight, Powdery Mildew\n🍚 Rice — Brown Spot, Stem Borer, Blast\n🍅 Tomato — Bacterial Wilt, Blight\n🥔 Potato — Late Blight, Scab\n\nUpload a photo in **Disease Detection** for instant AI diagnosis!" },
    { k:["wheat","gehu","गेहूं","rabi"], r:"🌾 **Wheat Farming Guide**\n\n📅 Sowing: Oct 15 – Nov 25\n🌡️ Temp: 20-25°C\n💧 Irrigation: 4-6 times/season\n🌱 Seed rate: 100-125 kg/ha\n📊 Expected yield: 3-4 tonnes/ha\n\nVarieties: HD-2967, PBW-343, GW-322\nFertilizer: N-120, P-60, K-40 kg/ha" },
    { k:["rice","chawal","dhaan","धान","paddy"], r:"🍚 **Rice Farming Guide**\n\n📅 Kharif sowing: June-July\n💧 Water: Keep field flooded 2-5cm\n🌱 Nursery: 25-30 days before transplant\n📊 Yield: 3-5 tonnes/ha\n\nVarieties: IR-64, Swarna, Pusa Basmati-1\nFertilizer: N-100, P-50, K-50 kg/ha" },
    { k:["tomato","tamatar","टमाटर"], r:"🍅 **Tomato Farming Guide**\n\n📅 Season: Sep-Oct or Feb-Mar\n🌱 Spacing: 60×45 cm\n💧 Drip irrigation recommended\n📊 Yield: 20-30 tonnes/ha\n\nFertilizer: N-100, P-80, K-60 kg/ha\nDisease watch: Bacterial wilt, Early blight" },
    { k:["maize","makka","मक्का","corn"], r:"🌽 **Maize Farming Guide**\n\n📅 Kharif: June-July | Rabi: Oct-Nov\n🌱 Seed rate: 20 kg/ha\n💧 Critical stages: Knee-high, tasseling\n📊 Yield: 4-6 tonnes/ha\n\nFertilizer: N-150, P-75, K-40 kg/ha" },
    { k:["potato","aalu","आलू"], r:"🥔 **Potato Farming Guide**\n\n📅 Planting: Oct-Nov (Rabi)\n🌱 Seed rate: 25-30 q/ha\n💧 Irrigation: Every 10-12 days\n📊 Yield: 20-30 tonnes/ha\n\nVarieties: Kufri Jyoti, Kufri Pukhraj\nWatch for: Late blight, Scab" },
    { k:["cotton","kapas","कपास"], r:"🌿 **Cotton Farming Guide**\n\n📅 Sowing: April-May (Kharif)\n🌱 Spacing: 90×60 cm\n💧 Critical: Boll formation stage\n📊 Yield: 15-20 q/ha (lint)\n\nVarieties: Bt Cotton hybrids\nWatch for: Bollworm, Whitefly" },
    { k:["soybean","soya","सोयाबीन"], r:"🫘 **Soybean Farming Guide**\n\n📅 Sowing: June-July (Kharif)\n🌱 Seed rate: 65-70 kg/ha\n💧 Rain-fed mostly, 3-4 irrigations\n📊 Yield: 1.5-2.5 tonnes/ha\n\nFertilizer: N-30, P-60, K-40 kg/ha\nRhizobium seed treatment recommended" },
    { k:["onion","pyaz","प्याज"], r:"🧅 **Onion Farming Guide**\n\n📅 Rabi: Oct-Nov | Kharif: June-July\n🌱 Transplant 6-week old seedlings\n💧 Irrigation: Every 8-10 days\n📊 Yield: 20-30 tonnes/ha\n\nVarieties: Nasik Red, Agrifound Light Red" },
    { k:["mustard","sarson","सरसों","canola"], r:"🌼 **Mustard Farming Guide**\n\n📅 Sowing: Oct-Nov (Rabi)\n🌱 Seed rate: 4-5 kg/ha\n💧 Irrigation: 2-3 times critical\n📊 Yield: 15-20 q/ha\n\nFertilizer: N-80, P-40, K-40 kg/ha\nAPEDA export quality varieties available" },
    { k:["pm-kisan","pmkisan","6000","2000"], r:"💰 **PM-KISAN Scheme**\n\n• Benefit: ₹6,000/year in 3 installments\n• Who: Farmers with land up to 2 hectares\n• Apply: pmkisan.gov.in\n• Docs: Aadhaar + bank account + land records\n\n📅 Installments: April, August, December\nCheck status: pmkisan.gov.in/Citizen_Corner" },
    { k:["pmfby","fasal bima","फसल बीमा","crop insurance"], r:"🛡️ **PMFBY — Crop Insurance**\n\n• Coverage: Up to 100% of insured amount\n• Premium: 2% Kharif, 1.5% Rabi, 5% Horticulture\n• Apply at your nearest bank or CSC center\n• Website: pmfby.gov.in\n\nDeadline: Before sowing season ends!" },
    { k:["kcc","kisan credit","किसान क्रेडिट","loan"], r:"💳 **Kisan Credit Card (KCC)**\n\n• Credit limit: Up to ₹3 lakh\n• Interest rate: 4% (with 3% govt subsidy)\n• Validity: 5 years with annual renewal\n• Apply at: Any bank branch or CSC\n\nDocuments: Land records, ID proof, passport photo" },
    { k:["pmksy","drip","sprinkler","sinchai","irrigation subsidy"], r:"💧 **PMKSY — Irrigation Scheme**\n\n• 55% subsidy on drip/sprinkler systems (SC/ST)\n• 45% subsidy for general farmers\n• Apply: pmksy.gov.in or district agriculture office\n\nBenefit: Save 40-50% water, increase yield by 30%!" },
    { k:["scheme","yojana","योजना","government","sarkar"], r:"📋 **Government Schemes for Farmers**\n\n💰 PM-KISAN — ₹6,000/year direct transfer\n🛡️ PMFBY — Crop insurance at low premium\n💳 KCC — Farm credit at 4% interest\n💧 PMKSY — Drip irrigation subsidy\n🌱 SHC — Free soil testing card\n🏪 eNAM — Online mandi platform\n\nVisit **Schemes** page for full details!" },
    { k:["soil","mitti","मिट्टी","loamy","clay","sandy","alluvial","black","red"], r:"🌱 **Soil Types & Best Crops**\n\n🟫 Alluvial — Wheat, Rice, Sugarcane (most fertile)\n⬛ Black (Regur) — Cotton, Soybean, Jowar\n🟥 Red — Groundnut, Millets, Tobacco\n🟤 Loamy — Best for most vegetables\n🔵 Sandy — Watermelon, Sweet potato\n\nGet soil tested free under Soil Health Card scheme!" },
    { k:["npk","nitrogen","phosphorus","potassium","urea","dap","fertilizer","khad","उर्वरक"], r:"💊 **Fertilizer Guide (NPK)**\n\n| Crop | N | P | K (kg/ha) |\n|------|---|---|---|\n| Wheat | 120 | 60 | 40 |\n| Rice | 100 | 50 | 50 |\n| Tomato | 100 | 80 | 60 |\n| Maize | 150 | 75 | 40 |\n| Cotton | 120 | 60 | 60 |\n\n💡 Apply nitrogen in 3 splits. Use soil test for precision." },
    { k:["organic","jaivik","जैविक","vermicompost","neem","compost"], r:"🌿 **Organic Farming Tips**\n\n1. Vermicompost (4-5 t/ha) for soil health\n2. Neem cake (200 kg/ha) as fertilizer+pesticide\n3. Cow dung slurry spray for leaf shine\n4. Crop rotation every season\n5. Green manuring (Dhaincha/Sunnhemp)\n\n✅ Organic produce sells 20-40% higher!\n🏪 List on our Marketplace for premium buyers" },
    { k:["weather","mausam","मौसम","rain","barish","बारिश","temp","humidity"], r:"🌤️ **Weather & Farming Tips**\n\n☀️ High temp (>35°C): Irrigate morning/evening only\n🌧️ Before rain: Don't spray pesticides/fungicides\n💨 High wind: Avoid spraying, risk of drift\n❄️ Cold (<10°C): Cover nursery seedlings at night\n🌫️ Foggy: Watch for fungal diseases (mildew, blight)\n\nVisit **Weather** page for city-wise 5-day forecast!" },
    { k:["yield","utpad","उत्पाद","production","per hectare","tonne"], r:"📊 **Average Yield Reference**\n\n🌾 Wheat: 3-4 t/ha (national avg 3.5)\n🍚 Rice: 2.5-3.5 t/ha\n🌽 Maize: 4-6 t/ha\n🍅 Tomato: 20-30 t/ha\n🥔 Potato: 20-25 t/ha\n☁️ Cotton: 1.5-2 t/ha lint\n🫘 Soybean: 1.5-2 t/ha\n\nUse **Yield Prediction** tool for your specific conditions!" },
    { k:["market","mandi","sell","becho","price","bhav","marketplace"], r:"🏪 **Marketplace Tips**\n\n• List crops directly — no middlemen!\n• Buyers contact you via WhatsApp\n• Organic produce gets 20-40% premium\n• Add photo + quality grade for better response\n\n→ Go to **Marketplace** page to list or browse crops\n→ Connect directly with buyers across India!" },
    { k:["water","sinchai","सिंचाई","drip","irrigation"], r:"💧 **Irrigation Guide**\n\n🌾 Wheat: 4-6 irrigations (CRI, jointing, flowering)\n🍚 Rice: Keep flooded 2-5cm always\n🍅 Tomato: Drip preferred, every 3-4 days\n🥔 Potato: Every 10-12 days, avoid waterlogging\n\n💡 Drip/Sprinkler saves 40% water + 55% subsidy (PMKSY)!" },
    { k:["seed","beej","बीज","variety","kism","किस्म"], r:"🌱 **Certified Seed Guide**\n\n• Always buy BIS certified seeds\n• Treat seeds before sowing (Thiram/Carbendazim)\n• Popular varieties:\n  🌾 Wheat: HD-3086, PBW-343, GW-322\n  🍚 Rice: IR-64, Swarna, Pusa Basmati\n  🌽 Maize: Pioneer 3396, DK 9141\n\nBuy from govt agri stores or online portals." },
    { k:["pest","keeda","कीड़े","locust","caterpillar","worm"], r:"🐛 **Pest Management**\n\n🔴 Stem Borer: Chlorpyrifos 2ml/L\n🔴 Aphids: Imidacloprid 0.5ml/L\n🔴 Whitefly: Yellow sticky traps + neem oil\n🔴 Caterpillar: Bt spray (Bacillus thuringiensis)\n🟡 IPM: Use pheromone traps for monitoring\n\n✅ Always spray early morning or late evening!" },
    { k:["harvest","katai","कटाई","cutting","threshing"], r:"🌾 **Harvest Tips**\n\n• Harvest at right moisture: Wheat 14%, Rice 18%\n• Avoid harvesting after rain (crop losses)\n• Use combine harvester for large fields\n• Proper drying before storage (8-12% moisture)\n• Storage: Use hermetic bags to prevent losses\n\n📊 Post-harvest losses in India: 10-15% — minimize with proper storage!" },
    { k:["storage","bhandaran","भंडारण","godown","warehouse"], r:"🏭 **Storage Best Practices**\n\n1. Dry grain to 12% moisture before storage\n2. Use hermetic bags (Purdue Improved Crop Storage)\n3. Fumigate godown with Celphos tablets\n4. Keep storage cool and dry\n5. Register with eNAM for warehouse receipts\n\nWMP (Warehouse Receipt): Get loans against stored grain!" },
    { k:["loan","karz","कर्ज","bank","credit","finance"], r:"💰 **Farm Credit Options**\n\n1. **KCC** — 4% interest, up to ₹3 lakh\n2. **MUDRA Loan** — Up to ₹10 lakh for agri business\n3. **NABARD** — Long term farm investment loans\n4. **PM SVANidhi** — For agri vendors ₹10,000-₹50,000\n\nApply at nearest bank branch or NABARD office." },
    { k:["profit","kamai","कमाई","income","revenue"], r:"💰 **How to Maximize Farm Income**\n\n1. Grow high-value crops (tomato, onion, vegetables)\n2. Go organic — 20-40% price premium\n3. Sell directly to buyers on Marketplace (no middlemen)\n4. Use govt schemes — PM-KISAN, KCC subsidy\n5. Multi-cropping — grow 2 crops/year on same land\n6. Value addition — sell processed products\n\n→ Visit **Marketplace** to connect with direct buyers!" },
    { k:["hello","hi","namaste","नमस्ते","helo","hey"], r:"🌾 **Namaste! I'm KrishiBot** 🤖\n\nYour AI Agriculture Assistant. Ask me about:\n\n🔬 Crop diseases & treatment\n🌱 Crop-wise farming guides (wheat, rice, tomato...)\n💊 Fertilizer & NPK recommendations\n💧 Irrigation & water management\n📋 Govt schemes (PM-KISAN, PMFBY, KCC)\n🌤️ Weather & sowing calendar\n🏪 Market prices & selling tips\n\nWhat would you like to know today?" },
  ],
  hi: [
    { k:["झुलसा","पत्ती","रोग","बीमारी"], r:"🔬 **पत्ती झुलसा रोग का उपचार**\n\n1. संक्रमित पत्तियां तुरंत हटाएं और जलाएं\n2. मैंकोजेब (2.5g/L) हर 7-10 दिन में लगाएं\n3. ऊपर से सिंचाई न करें\n4. प्रतिरोधी किस्में उपयोग करें\n\nरोग पहचान के लिए फोटो अपलोड करें! 🌿" },
    { k:["माहू","कीड़ा","कीट"], r:"🐛 **माहू (एफिड) नियंत्रण**\n\n1. इमिडाक्लोप्रिड (0.5ml/L) छिड़काव\n2. नीम तेल (5ml/L) जैविक नियंत्रण\n3. पीले चिपचिपे ट्रैप लगाएं\n4. गेंदा फूल ट्रैप क्रॉप लगाएं\n\nसुबह या शाम को छिड़काव करें!" },
    { k:["गेहूं","गेहु","रबी"], r:"🌾 **गेहूं खेती गाइड**\n\n📅 बुवाई: 15 अक्टूबर – 25 नवंबर\n🌡️ तापमान: 20-25°C\n💧 सिंचाई: 4-6 बार प्रति सीजन\n🌱 बीज दर: 100-125 kg/हेक्टेयर\n📊 उपज: 3-4 टन/हेक्टेयर\n\nकिस्में: HD-2967, PBW-343, GW-322\nउर्वरक: N-120, P-60, K-40 kg/ha" },
    { k:["धान","चावल","खरीफ"], r:"🍚 **धान खेती गाइड**\n\n📅 बुवाई: जून-जुलाई\n💧 खेत में 2-5cm पानी भरा रखें\n🌱 नर्सरी: रोपाई से 25-30 दिन पहले\n📊 उपज: 3-5 टन/हेक्टेयर\n\nकिस्में: IR-64, स्वर्णा, पूसा बासमती-1\nउर्वरक: N-100, P-50, K-50 kg/ha" },
    { k:["टमाटर","tamatar"], r:"🍅 **टमाटर खेती गाइड**\n\n📅 मौसम: सितंबर-अक्टूबर या फरवरी-मार्च\n🌱 दूरी: 60×45 cm\n💧 ड्रिप सिंचाई सर्वोत्तम\n📊 उपज: 20-30 टन/हेक्टेयर\n\nउर्वरक: N-100, P-80, K-60 kg/ha\nरोग: जीवाणु म्लानि, पत्ती झुलसा से बचाव करें" },
    { k:["आलू"], r:"🥔 **आलू खेती गाइड**\n\n📅 बुवाई: अक्टूबर-नवंबर\n🌱 बीज दर: 25-30 क्विंटल/हेक्टेयर\n💧 सिंचाई: हर 10-12 दिन में\n📊 उपज: 20-30 टन/हेक्टेयर\n\nकिस्में: कुफरी ज्योति, कुफरी पुखराज\nदेर से झुलसा रोग से सावधान रहें" },
    { k:["उर्वरक","खाद","यूरिया","DAP","NPK","नाइट्रोजन"], r:"💊 **उर्वरक सारणी**\n\n| फसल | नाइट्रोजन | फास्फोरस | पोटेशियम |\n|------|-----------|-----------|----------|\n| गेहूं | 120 | 60 | 40 |\n| चावल | 100 | 50 | 50 |\n| टमाटर | 100 | 80 | 60 |\n| मक्का | 150 | 75 | 40 |\n\n💡 नाइट्रोजन को 3 बार में डालें। मिट्टी जांच करवाएं।" },
    { k:["PM-KISAN","किसान","योजना","6000","पीएम किसान"], r:"💰 **PM-KISAN योजना**\n\n• लाभ: ₹6,000/वर्ष — 3 किस्तों में\n• पात्र: 2 हेक्टेयर तक भूमि वाले किसान\n• आवेदन: pmkisan.gov.in\n• दस्तावेज: आधार, बैंक खाता, भूमि रिकॉर्ड\n\n📅 किस्तें: अप्रैल, अगस्त, दिसंबर" },
    { k:["बीमा","PMFBY","फसल बीमा"], r:"🛡️ **PMFBY फसल बीमा**\n\n• कवरेज: बीमित राशि का 100% तक\n• प्रीमियम: खरीफ 2%, रबी 1.5%\n• नजदीकी बैंक या CSC केंद्र में आवेदन\n• वेबसाइट: pmfby.gov.in\n\nबुवाई से पहले आवेदन जरूर करें!" },
    { k:["जैविक","नीम","वर्मीकम्पोस्ट","organic"], r:"🌿 **जैविक खेती**\n\n1. वर्मीकम्पोस्ट (4-5 टन/हेक्टेयर)\n2. नीम केक (200 kg/ha) — उर्वरक + कीटनाशक\n3. गोमूत्र स्प्रे — पत्ती स्वास्थ्य के लिए\n4. हर मौसम में फसल चक्र\n5. हरी खाद (ढैंचा/सनई)\n\n✅ जैविक फसल 20-40% अधिक मूल्य पाती है!" },
    { k:["मौसम","बारिश","तापमान","पूर्वानुमान"], r:"🌤️ **मौसम और खेती सलाह**\n\n☀️ अधिक गर्मी: सुबह/शाम सिंचाई करें\n🌧️ बारिश से पहले: कीटनाशक न छिड़कें\n❄️ सर्दी (<10°C): नर्सरी ढकें\n🌫️ कोहरा: कवक रोगों पर नजर रखें\n\nशहर के मौसम के लिए **Weather** पेज देखें!" },
    { k:["मंडी","बेचना","भाव","बाजार"], r:"🏪 **मंडी और बाजार**\n\n• हमारे Marketplace पर सीधे खरीदार से मिलें\n• कोई बिचौलिया नहीं — पूरा पैसा आपका!\n• जैविक फसल के लिए 20-40% अधिक दाम\n• WhatsApp से सीधे संपर्क\n\n→ **Marketplace** पेज पर जाएं और अपनी फसल सूचीबद्ध करें!" },
    { k:["नमस्ते","हेलो","hello","hi"], r:"🌾 **नमस्ते! मैं KrishiBot हूं** 🤖\n\nआपका AI कृषि सहायक। मुझसे पूछें:\n\n🔬 फसल रोग और उपचार\n🌱 खेती की पूरी जानकारी\n💊 उर्वरक और NPK सलाह\n💰 सरकारी योजनाएं\n🌤️ मौसम और बुवाई समय\n🏪 मंडी और बाजार भाव\n\nआज क्या जानना चाहते हैं?" },
  ],
};

const getLocalReply = (message, lang) => {
  const msg = message.toLowerCase();
  const list = lang === "hi" ? KB.hi : KB.en;
  for (const item of list) {
    if (item.k.some(k => msg.includes(k.toLowerCase()))) return item.r;
  }
  // If no match — try English list as fallback even for Hindi queries
  for (const item of KB.en) {
    if (item.k.some(k => msg.includes(k.toLowerCase()))) return item.r;
  }
  return lang === "hi"
    ? "🌾 **KrishiBot यहाँ है!**\n\nमैं इन विषयों पर मदद कर सकता हूं:\n• गेहूं, चावल, टमाटर, आलू, मक्का की खेती\n• फसल रोग पहचान और उपचार\n• उर्वरक और सिंचाई सलाह\n• PM-KISAN, PMFBY, KCC योजनाएं\n• मंडी और बाजार भाव\n\nकृपया थोड़ा विस्तार से पूछें!"
    : "🌾 **KrishiBot here!**\n\nI can help with:\n• Wheat, rice, tomato, potato, maize farming\n• Crop disease identification & treatment\n• Fertilizer & irrigation advice\n• PM-KISAN, PMFBY, KCC schemes\n• Market prices & selling tips\n\nPlease ask in a bit more detail!";
};

export default getLocalReply;
